OPTION_1=Operación exenta del Impuesto sobre el Valor Añadido
OPTION_2=Medio de transporte
OPTION_3=Facturación por el destinatario
OPTION_4=Inversión del sujeto pasivo
OPTION_5=Régimen especial de las agencias de viajes
OPTION_6=Régimen especial de los bienes usados
OPTION_7=Régimen especial de los objetos de arte
OPTION_8=Régimen especial de las antigüedades y objetos de colección
OPTION_9=Régimen especial del criterio de caja

TEXT_1=Operación exenta por aplicación del artículo [indicar el artículo] de la Ley 37/1992, de 28 de diciembre, del Impuesto sobre el Valor Añadido
TEXT_2=Medio de transporte [describir el medio, por ejemplo automóvil turismo Seat Ibiza TDI 2.0] fecha 1ª puesta en servicio [indicar la fecha] distancias/horas recorridas [indicar la distancia o las horas, por ejemplo, 5.900 km o 48 horas]
TEXT_3=Facturación por el destinatario
TEXT_4=Inversión del sujeto pasivo
TEXT_5=Régimen especial de las agencias de viajes
TEXT_6=Régimen especial de los bienes usados
TEXT_7=Régimen especial de los objetos de arte
TEXT_8=Régimen especial de las antigüedades y objetos de colección
TEXT_9=Régimen especial del criterio de caja.
