# Fichero de configuración del validador de la policy FacturaE

# Identidad que se espera en el campo de identificador 
age18.policy.id=urn:oid:2.16.724.1.3.1.1.2.1.8
age19.policy.id=urn:oid:2.16.724.1.3.1.1.2.1.9

# Mensaje de identificación del validador
age18.policy.idValidator=Politica de Firma AGE v1.8
age19.policy.idValidator=Politica de Firma AGE v1.9

# Dirección de descarga de la política
age18.policy.spuri=http://administracionelectronica.gob.es/es/ctt/politicafirma/politica_firma_AGE_v1_8.pdf
#age19.policy.spuri=http://administracionelectronica.gob.es/es/ctt/politicafirma
age19.policy.spuri=https://sede.060.gob.es/politica_de_firma_anexo_1.pdf

# Mensaje de descripción de la policy
age18.policy.description=Política de firma electrónica para la Administración General del Estado
age19.policy.description=Política de firma electrónica para la Administración General del Estado

# Posibles digest que se validan en el campo de huella digital. Estos campos se parametrizan con el formato:
#   policy.digest.xx.##
# donde xx puede tener:
#   id para identificar el tipo de algoritmo de huello digital
#   value para indicar el valor en base64 del cálculo de la huella de la policy
# y ## tiene un número que se incrementa consecutivamente por cada tipo de algoritmo de hash 
age18.policy.digest.id.0=http://www.w3.org/2000/09/xmldsig#sha1
age18.policy.digest.value.0=V8lVVNGDCPen6VELRD1Ja8HARFk=
age18.policy.digest.id.1=http://www.w3.org/2001/04/xmldsig-more#hmac-sha256
age18.policy.digest.value.1=Vnu5UQhyEgbezgIVbNl/0szpYEBKlswmpJiXdtB0aiU=
age18.policy.digest.id.2=http://www.w3.org/2000/09/xmldsig#sha1
age18.policy.digest.value.2=VYICYpNOjso9g1mBiXDVxNORpKk=

age19.policy.digest.id.0=http://www.w3.org/2000/09/xmldsig#sha1
age19.policy.digest.value.0=Cs+vY02TTHJxT3FskFj0Vbf05O4=
age19.policy.digest.id.1=http://www.w3.org/2001/04/xmldsig-more#hmac-sha256
age19.policy.digest.value.1=9fYN37XfU+PnhTloEjrMHIIAWTLOMMn88PTyBZgaT+Q=
age19.policy.digest.id.2=http://www.w3.org/2000/09/xmldsig#sha1
age19.policy.digest.value.2=G7roucf600+f03r/o0bAOQ6WAs0=
 
# Digest que se escribirá de la política (el número ha de estar representado con un id en el listado de digest anterior)
age18.policy.writer.digest=0
age19.policy.writer.digest=0
