# En este fichero se indica qué clases son las encargadas de validar policies
# específicas
# Formato:
#   <clave>=<clase>
# donde clave puede ser cualquier string que no contenga un código especial 
# (por ejemplo un hash en hexadecimal de la policy), y clase es la clase
# que implementa el interfaz es.mityc.firmaJava.policy.IValidacionPolicy
facturae30=es.mityc.javasign.xml.xades.policy.facturae.Facturae30Manager
1d0bcf7a68c3b2556970d99a24fa5b1f385d679d=es.mityc.javasign.xml.xades.policy.facturae.Facturae30Manager
a60ee2a62d842843650058a6b77815ac04b794f6f3fd56df12acb98fc4b51636=es.mityc.javasign.xml.xades.policy.facturae.Facturae30Manager
facturae31=es.mityc.javasign.xml.xades.policy.facturae.Facturae31Manager
3a18b197aba90fa6aff0dee912f0c006110bea13=es.mityc.javasign.xml.xades.policy.facturae.Facturae31Manager
6bfbc3a2e789abdcf1586085c1db177655ed9054847a4e1756d9a5402103684f=es.mityc.javasign.xml.xades.policy.facturae.Facturae31Manager
notransforms=es.mityc.javasign.xml.xades.policy.NoTransformsPolicy
age18=es.mityc.javasign.xml.xades.policy.age.Age18Manager
age19=es.mityc.javasign.xml.xades.policy.age.Age19Manager
55820262934e8eca3d8359818970d5c4d391a4a9=es.mityc.javasign.xml.xades.policy.age.Age18Manager
57c95554d18308f7a7e9510b443d496bc1c04459=es.mityc.javasign.xml.xades.policy.age.Age18Manager

0acfaf634d934c72714f716c9058f455b7f4e4ee=es.mityc.javasign.xml.xades.policy.age.Age19Manager
#567bb95108721206dece02156cd97fd2cce960404a96cc26a4989776d0746a25=es.mityc.javasign.xml.xades.policy.age.Age18Manager
567bb95108721206dece02156cd97fd2cce960404a96cc26a4989776d0746a25=es.mityc.javasign.xml.xades.policy.age.Age19Manager
1bbae8b9c7fad34f9fd37affa346c0390e9602cd=es.mityc.javasign.xml.xades.policy.age.Age19Manager
